### ISSUE TITLE
Indoor scene reconstruction

### ISSUE THREAD

**Issue by zz7379** [monniert/differentiable-blocksworld#4]
I am wondering that is it possible to use this method for Indoor scene reconstruction?

**Comment by monniert** [comment]
Hi zz7379, thanks for the interest!

What do you mean by indoor scenes? In general, it would work for scenes where the desired content to reconstruct is close to the camera and the background is relatively farther from the camera so that it can be modeled by the background dome. For example, this is the case for the gundam, the multi cylinder or the campanile scenes. I think it would struggle for scenes like rooms from ScanNet where the desired content to reconstruct is the entire room. That said, it is worth trying with a very far background dome, the superquadrics may reconstruct the walls.

Hope this helps, feel free to reopen if you have questions!
